#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

check_run() {
	if [ $(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD | grep -c "package.json") -gt 0 ]
	then
		{{PACKAGE_MANAGER}} install
	fi
}

check_run
